name: Build Bihoosh Android

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:

      # دریافت پروژه بی‌هوش
      - name: Checkout Bihoosh
        uses: actions/checkout@v4


      # Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"


      # Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: 'platform-tools'


      # Android SDK / NDK / CMake
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses || true

          sdkmanager \
            "platform-tools" \
            "platforms;android-36" \
            "build-tools;36.0.0" \
            "ndk;29.0.13113456" \
            "cmake;3.31.6"


      # دریافت llama.cpp رسمی
      - name: Download llama.cpp
        run: |
          git clone \
            --depth 1 \
            https://github.com/ggml-org/llama.cpp.git \
            llama.cpp


      # دریافت Android Native Bridge رسمی
      - name: Download llama Android native bridge
        run: |

          curl -L \
            https://raw.githubusercontent.com/ggml-org/llama.cpp/master/examples/llama.android/lib/src/main/cpp/ai_chat.cpp \
            -o android/lib/src/main/cpp/ai_chat.cpp

          curl -L \
            https://raw.githubusercontent.com/ggml-org/llama.cpp/master/examples/llama.android/lib/src/main/cpp/logging.h \
            -o android/lib/src/main/cpp/logging.h


      # Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.13"


      # ساخت APK
      - name: Build Debug APK
        working-directory: android
        run: |
          gradle :app:assembleDebug --no-daemon


      # آپلود APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Bihoosh-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
